# reusable workflow to run all tests
name: run-tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      install-script:
        required: true
        type: string
      dotnet-runtime:
        required: false
        type: string
        default: mono # or coreclr, netfx
jobs:
  run-tests:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
    - name: Configure .NET runtime
      shell: bash -l {0}
      run: |
        if [ "${{ inputs.dotnet-runtime }}" = "mono" ] && [ "$RUNNER_OS" = "Windows" ]; then
          echo "ALPHARAW_DOTNET_RUNTIME=netfx" >> "$GITHUB_ENV"
        else
          echo "ALPHARAW_DOTNET_RUNTIME=${{ inputs.dotnet-runtime }}" >> "$GITHUB_ENV"
        fi
    - name: Install .NET runtime (for coreclr only)
      if: ${{ inputs.dotnet-runtime == 'coreclr' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Perform pip installation
      shell: bash -l {0}
      run: |
        cd misc
        . ./${{ inputs.install-script }} alpharaw ${{ inputs.python-version }} "$ALPHARAW_DOTNET_RUNTIME"
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate alpharaw
        cd tests
        python download_test_data.py
        . ./run_tests.sh
        conda deactivate
