# reusable workflow to run all tests
name: run-tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      install-script:
        required: true
        type: string
jobs:
  run-tests:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
    - name: Install mono
      shell: bash -l {0}
      run: |
        if [ "$RUNNER_OS" != "Windows" ]; then
          conda install -y mono
        fi
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Install mono
      if: ${{ !contains(inputs.os, 'windows') }}
      shell: bash -l {0}
      run: |
        conda install mono
    - name: Perform pip installation
      shell: bash -l {0}
      run: |
        cd misc
        . ./${{ inputs.install-script }} alpharaw ${{ inputs.python-version }} ${{ !contains(inputs.os, 'windows') }}
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate alpharaw
        cd tests
        python download_test_data.py
        . ./run_tests.sh
        conda deactivate
